var express_=require("express")
var routing=require("./routing/user_routing")
var adminrouting=require("./routing/adminRouting")
var db=require("./database/user_db")
var cors_=require("cors")
var myapp=express_()
myapp.listen(5000,()=>{ console.log("server created");})

myapp.get("/",(req,res)=>{
    console.log("welcome ecommerces")
    res.send("welcome ecommerces")
})
myapp.use(cors_())
myapp.use(express_.urlencoded({extended:false}))
myapp.use(express_.json())
myapp.use("/user",routing)
myapp.use("/admin",adminrouting)
